// Auth actions
export const SET_AUTH = 'SET_AUTH';

// User actions
export const GET_USER_START = 'GET_USER_START';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const GET_USER_END = 'GET_USER_END';

// Class actions
export const GET_CLASSES_START = 'GET_CLASSES_START';
export const GET_CLASSES_ERROR = 'GET_CLASSES_ERROR';
export const GET_CLASSES_END = 'GET_CLASSES_END';
export const DELETE_CLASS_START = 'DELETE_CLASS_START';
export const DELETE_CLASS_ERROR = 'DELETE_CLASS_ERROR';
export const DELETE_CLASS_END = 'DELETE_CLASS_END';
export const EDIT_CLASS_START = 'EDIT_CLASS_START';
export const EDIT_CLASS_ERROR = 'EDIT_CLASS_ERROR';
export const EDIT_CLASS_END = 'EDIT_CLASS_END';

// Collect actions
export const BEGIN_COLLECT_START = 'BEGIN_COLLECT_START';
export const BEGIN_COLLECT_ERROR = 'BEGIN_COLLECT_ERROR';
export const BEGIN_COLLECT_END = 'BEGIN_COLLECT_END';
export const STOP_COLLECT_START = 'STOP_COLLECT_START';
export const STOP_COLLECT_ERROR = 'STOP_COLLECT_ERROR';
export const STOP_COLLECT_END = 'STOP_COLLECT_END';
